[package]
name = "connect4win"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
yew = { version = "0.20", features = ["csr"] }

#[target.'cfg(target_family = "wasm")'.dependencies]
#yew = { version = "0.20", features = ["csr"] }