[application]

# dioxus project name
name = "connect4win"

# default platfrom
# you can also use `dx serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "connect4win"

[web.watcher]

index_on_404 = true

watch_path = ["src"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[application.plugins]

available = true

required = []

[bundler]
# Bundle identifier
identifier = "io.github.connect4win"

# Bundle publisher
publisher = "connect4win"

# Bundle icon
icon = ["icons/icon.png"]

# Bundle resources
resources = ["public/*"]

# Bundle copyright
copyright = ""

# Bundle category
category = "Utility"

# Bundle short description
short_description = "A connect-four game engine"

# Bundle long description
long_description = """
A connect-four game engine.
"""